# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d964bf2d17be371997efc53f337945b8d6ef06d67949b9482a6f95c2018890bbff572d7fbfc60fa1a647d4e1b47f9a279f33e3aa2ebe962cafe15757497412

test:
  secret_key_base: b561c2ee53ed2c6acfa844dc46b82c876d6c9ccb422f0fbc0b066c9176e958c56b7d8158f0be4d6062dc3ab984aaa27c30fa278a16293d2342f7afc5f658f846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
